name: ecommerce
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  carousel_slider: ^2.3.1
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.2
  firebase_core: ^0.5.1
  firebase_storage: ^4.0.1
  flutter_slidable: ^0.5.7
  flutter_staggered_grid_view: ^0.3.2
  flutter_svg: null
  fluttertoast: ^7.1.6
  font_awesome_flutter: ^8.10.0
  google_fonts: null
  google_sign_in: ^4.5.9
  image_picker: ^0.6.7+17
  path: ^1.7.0
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+2
  flutter_facebook_login: ^3.0.0
  rxdart: ^0.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter

module:
  androidX: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
